name: build metasploit-framework

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 1,15 * *'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Clone metasploit-framework repo
        uses: actions/checkout@v4
        with:
          repository: rapid7/metasploit-framework
          path: metasploit-framework
      - run: |
          echo "MSFV=$(perl -ne '/metasploit-framework\s*\((.*?)\)/ && print $1' metasploit-framework/Gemfile.lock)-dev" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: metasploit-framework
          push: true
          tags: scmanjarrez/metasploit-framework:latest,scmanjarrez/metasploit-framework:${{ env.MSFV }}
          platforms: linux/amd64,linux/arm64
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
